version: "3"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"  # Enable the dashboard (optional)
      - "--providers.docker=true"  # Enable Docker provider
      - "--entrypoints.web.address=:80"  # HTTP
      # Remove or comment out HTTPS-related configuration since we don't need it locally
      # - "--entrypoints.websecure.address=:443"  # HTTPS
      # - "--certificatesresolvers.myresolver.acme.httpchallenge=true"  # ACME certificate resolver
      # - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"  # Use the web entrypoint for HTTP challenge
      # - "--certificatesresolvers.myresolver.acme.email=fongren007@gmail.com"  # Email for Let's Encrypt (not needed for local)
      # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"  # Remove if no ACME
    ports:
      - "80:80"  # HTTP
      # Remove the port 443 for HTTPS if SSL is not needed locally
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Allow Traefik to interact with Docker
      - "./letsencrypt:/letsencrypt"  # Store Let's Encrypt certificates (this can be removed if not using ACME)

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Allow Portainer to access Docker
      - "portainer_data:/data"  # Store Portainer data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`localhost`, `www.localhost`)"  # Use localhost instead of domain
      - "traefik.http.routers.portainer.entrypoints=web"  # Use HTTP instead of HTTPS (since we're not using SSL for local)
      # Remove SSL-related labels for local testing
      # - "traefik.http.routers.portainer.tls=true"  # No TLS
      # - "traefik.http.routers.portainer.tls.certresolver=myresolver"  # No SSL certificate resolver
    restart: always

volumes:
  portainer_data:  
