version: '3.8'

services:
  app:
    build: .
    container_name: frontend_school
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
