version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_school
    volumes:
      - .:/app # Mount local directory to the container
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80" # Expose Vite's default port
    environment:
      - NODE_ENV=development
