version: '3.8'

services:
  app:
    image: nasfong/backend_school:latest
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=mongodb://nasfong:GZjWruInjQ@nasfong.site:27017/school
    networks:
      - mongo_net
    depends_on:
      - mongodb  # This ensures that the app waits for MongoDB

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  # MongoDB default port
    volumes:
      - mongo_data:/data/db  # Persist data
    networks:
      - mongo_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: nasfong
      MONGO_INITDB_ROOT_PASSWORD: GZjWruInjQ

volumes:
  mongo_data:

networks:
  mongo_net:
    external: true  # Reuse the same external overlay network
